### PR TITLE
style(type-colors) use bootstrap colors for notification types

### LINKED ISSUE #11: Change color of success notification to green
"Success" feedback is usually shown in green. The success notification container should be green instead of the current pale yellow

### PR DESCRIPTION
**Pull request by sarahsga**
This PR resolves #11
notifier

### CODE REVIEW

**Comment by dominique-mueller** [comment]
Awesome! Thanks again for contributing 👍

**Comment by sarahsga** [comment]
I guess the docs gif needs to be updated too. Will do that

**Comment by dominique-mueller** [comment]
If you find the time, that'll be awesome.

**Comment by dominique-mueller** [comment]
I've used **[ScreenToGif](https://screentogif.codeplex.com/)** to create it, and exported it with all size optimizations possible.

**Pull request merged**
