### PR TITLE
Update GIF to show new colors

### PR DESCRIPTION
**Pull request by sarahsga**
Updated gif for #11

### CODE REVIEW

**Comment by dominique-mueller** [comment]
Could you record the GIF with 60 frames / second? Looks a bit laggy right now ...

**Comment by sarahsga** [comment]
Any idea why the README still shows the old gif after the merge?

**Comment by dominique-mueller** [comment]
I assume that's chaching. Let's hope the new GIF gets shown within the next 24 to 48 hours.

**Comment by dominique-mueller** [comment]
Ah, just checked again, my browser now shows me the new GIF in the README.

**Pull request merged**
